TaskManager/Models/Helpers.cs
using Amazon;
using Amazon.DynamoDBv2;
using Amazon.Runtime;

namespace TaskManager.Models
{
    public static class Helpers
    {
        // const string ACCESS_KEY = ;
        // const string SECRET_KEY = ;
        const string TABLE_NAME = "Tasks";

        public static AmazonDynamoDBClient GetDynamoDbClient()
        {
            var cred = new BasicAWSCredentials(ACCESS_KEY, SECRET_KEY);
            var region = RegionEndpoint.USEast2;

            return new AmazonDynamoDBClient(cred, region);
        }
            


    }
}

TaskManager/Models/SubTaskItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TaskManager.Models
{
    public class SubTaskItem
    {
        public int sub_task_id { get; set; }
        public string description { get; set; }
        public int parent_task_id { get; set; }
    }
}

TaskManager/Models/TaskItem.cs
using Amazon.DynamoDBv2.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TaskManager.Models
{
    [DynamoDBTable("Tasks")]
    public class TaskItem
    {
        [DynamoDBHashKey]
        public Guid task_id { get; set; }
        public TaskState state { get; set; }
        public string description { get; set; }
        public string long_description { get; set; }
        public IEnumerable<string> subtasks { get; set; }
        public string priority { get; set; }
        public DateTime date_due { get; set; }
    }

    public enum TaskState
    {
        Todo,
        InProgress,
        Done,
        Cancelled,
    };
}

TaskManager/Pages/EditTask.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Amazon.DynamoDBv2.DataModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TaskManager.Models;
using Amazon.DynamoDBv2.DocumentModel;

namespace TaskManager.Pages
{
    public class EditTaskModel : PageModel
    {
        public TaskItem EditTask { get; set; }

        public async Task OnGetAsync(Guid task_id)
        {
            EditTask = await GetEditTask(task_id);
        }

        public async Task<IActionResult> OnPostAsync(TaskItem task)
        {
            var client = Helpers.GetDynamoDbClient();
            var ctx = new DynamoDBContext(client);
            await ctx.SaveAsync(task);

            return RedirectToPage("Index");
        }

        private async Task<TaskItem> GetEditTask(Guid task_id)
        {
            var client = Helpers.GetDynamoDbClient();
            var ctx = new DynamoDBContext(client);

            return await ctx.LoadAsync<TaskItem>(task_id);
        }
    }
}

TaskManager/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TaskManager.Models;
using Amazon.DynamoDBv2.DataModel;

namespace TaskManager.Pages
{
    public class IndexModel : PageModel
    {
        public TaskItem Task { get; set; }
        public IEnumerable<TaskItem> Tasks { get; set; }

        public async Task OnGetAsync()
        {
            var client = Helpers.GetDynamoDbClient();
            List<ScanCondition> conditions = new List<ScanCondition>();
            DynamoDBContext ctx = new DynamoDBContext(client);
            Tasks = await ctx.ScanAsync<TaskItem>(conditions).GetRemainingAsync();
        }

        public async Task<IActionResult> OnPostAddAsync(TaskItem task)
        {
            task.task_id = Guid.NewGuid();

            var client = Helpers.GetDynamoDbClient();
            DynamoDBContext ctx = new DynamoDBContext(client);
            await ctx.SaveAsync(task);

            return RedirectToAction(Request.ToString());
        }

        public IActionResult OnPostEdit(Guid task_id)
        {
            return RedirectToPage("EditTask", new { task_id });
        }

        public async Task<IActionResult> OnPostRemove(Guid task_id)
        {
            var client = Helpers.GetDynamoDbClient();
            DynamoDBContext ctx = new DynamoDBContext(client);
            await ctx.DeleteAsync<TaskItem>(task_id);

            return RedirectToAction(Request.ToString());
        }
    }
}

TaskManager/Pages/EditTask.cshtml
@page
@using TaskManager.Models
@model EditTaskModel
@{
}

<form method="post">
    <input type="hidden" name="task_id" value="@Model.EditTask.task_id" asp-for="EditTask.task_id" />
    <div class="row mb-1">
        <input type="text" class="form-control col-6" name="description" value="@Model.EditTask.description" asp-for="EditTask.description" />
    </div>

    <div class="row mb-1">
        <textarea class="form-control col-6" name="long_description" value="@Model.EditTask.long_description" asp-for="EditTask.long_description" rows="3"></textarea>
    </div>

    <div class="row mb-1">
        <div class="input-group date" data-provide="datepicker">
            <input type="text" class="form-control col-3" name="date_due" value="@Model.EditTask.date_due.ToShortDateString()" asp-for="EditTask.date_due" />
            <div class="input-group-addon">
                <span class="glyphicon glyphicon-th"></span>
            </div>
        </div>
    </div>

    <div class="row mb-1">
        <select class="form-control col-3" name="state" asp-for="EditTask.state" asp-items="Html.GetEnumSelectList<TaskState>()"></select>
    </div>

    <div class="row mb-1">
        <select class="form-control col-3" name="priority" asp-for="EditTask.priority">
            <option value="none">-- Select Priority --</option>
            <option value="high">High</option>
            <option value="med">Medium</option>
            <option value="low">Low</option>
        </select>
    </div>

    <div class="row mb-4">
        <button type="submit" class="btn btn-outline-secondary" asp-page-handler="Edit">Edit Task</button>
    </div>
</form>

TaskManager/Pages/Index.cshtml
@page
@using Models
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@{
    string GetStateColor(TaskItem task)
    {
        var stateColor = "";
        switch (task.state)
        {
            case TaskState.Todo:
                stateColor = "color:red";
                break;
            case TaskState.Done:
                stateColor = "color:green";
                break;
            case TaskState.Cancelled:
                stateColor = "color:red; text-decoration:line-through";
                break;
            default:
                stateColor = "color:black";
                break;
        }

        return stateColor;
    }

}

<div class="row mb-4">
    <h2>Task Manager</h2>
</div>

<form method="post">
    <div class="row mb-1">
        <input type="text" class="form-control col-6" placeholder="New Task" asp-for="Task.description" />
    </div>

    <div class="row mb-1">
        <textarea class="form-control col-6" asp-for="Task.long_description" rows="3" placeholder="Description of task"></textarea>
    </div>

    <div class="row mb-1">
        <div class="input-group date" data-provide="datepicker">
            <input type="text" class="form-control col-3" placeholder="Due Date" asp-for="Task.date_due" />
            <div class="input-group-addon">
                <span class="glyphicon glyphicon-th"></span>
            </div>
        </div>
    </div>

    <div class="row mb-1">
        <select class="form-control col-3" asp-for="Task.state" asp-items="Html.GetEnumSelectList<TaskState>()"></select>
    </div>

    <div class="row mb-1">
        <select class="form-control col-3" asp-for="Task.priority">
            <option value="none">-- Select Priority --</option>
            <option value="high">High</option>
            <option value="med">Medium</option>
            <option value="low">Low</option>
        </select>
    </div>

    <div class="row mb-4">
        <button type="submit" class="btn btn-outline-secondary" asp-page-handler="Add">Add Task</button>
    </div>
</form>

<div class="row mb-2">
    <h4>Current Tasks</h4>
</div>

<div class="row">
    <ul class="list-unstyled">
        @if (Model.Tasks != null)
        {
            @foreach (var task in Model.Tasks)
            {
            <li class="list-group-item">
                <span style="@GetStateColor(task); font-weight:bold" class="mr-2">@task.state</span>
                <span class="mr-2">@task.description</span>
                <span class="mr-2">@task.date_due.ToShortDateString()</span>
                <span>@task.priority.ToUpper()</span>
                <form method="post" asp-page="Index" asp-page-handler="Edit" style="display: inline">
                    <input type="hidden" name="task_id" value="@task.task_id" />
                    <button type="submit" class="btn btn-link"><span class="fa fa-edit"></span></button>
                </form>
                <form method="post" asp-page="Index" asp-page-handler="Remove" style="display: inline">
                    <input type="hidden" name="task_id" value="@task.task_id" />
                    <button type="submit" class="btn btn-link"><span class="fa fa-trash"></span></button>
                </form>
                <br/>
                <ul class="list-unstyled">
                    <li class="list-group-item">
                        @task.long_description
                    </li>
                </ul>
            </li>
            }
        }
    </ul>
</div>

TaskManager/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskManager</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body>
    @*<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">TaskManager</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - TaskManager</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>